In [1]:
import numpy as np

## Comparing the utility of list and numpy array

#### Time how long it takes to square all values in a sequence using list

In [2]:
def squares(values):
    result = []
    for v in values:
        result.append(v * v)
    return result
# create 100,000 numbers using python range
to_square = range(100000)
# time how long it takes to repeatedly square them all
%timeit squares(to_square)

5.43 ms ± 294 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [3]:
array_to_square = np.arange(0,100000)
%timeit array_to_square**2

105 µs ± 34.2 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


## Creating a numpy array from list

In [4]:
a1 = np.array([2,4,6,8])
a1

array([2, 4, 6, 8])

### Determing its Type 

In [5]:
type(a1)

numpy.ndarray

### Claculating number of its element

In [6]:
np.size(a1)

4

In [7]:
a2 = np.array([1,2,3,4.6])
np.size(a2)

4

### Evaluating the Dimension type in an array

In [8]:
a2.dtype

dtype('float64')

## Several ways to create numpy array

#### 1. Shorthand to repeat a sequence 10 times

In [9]:
a3 = np.array([0]*10)
a3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 2. Use python range fumction to create numpy array

In [10]:
a4 = np.array(range(10))
a4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 3.a Use of np.zeros() function (float type)

In [11]:
a5 = np.zeros(10)
a5

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3.b Use of np.zeros() function (int type)

In [12]:
a6 = np.zeros(10, dtype = int)
a6

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4 Use of np.arange() function 

In [13]:
a7 = np.arange(0,10)
a7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 4b. Use of np.arange() function with step value

In [14]:
# Table of 2
a8 = np.arange(2,22,2)
a8

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [15]:
# Reverse table of 2
a9 = np.arange(20,0,-2)
a9

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### 5. Use of np.linspace() function

In [16]:
a10 = np.linspace(5,55,20)
a10

array([ 5.        ,  7.63157895, 10.26315789, 12.89473684, 15.52631579,
       18.15789474, 20.78947368, 23.42105263, 26.05263158, 28.68421053,
       31.31578947, 33.94736842, 36.57894737, 39.21052632, 41.84210526,
       44.47368421, 47.10526316, 49.73684211, 52.36842105, 55.        ])

#### Eventhough default data type is float it can be changed

In [17]:
a11 = np.linspace(5,55,20,dtype = int)
a11

array([ 5,  7, 10, 12, 15, 18, 20, 23, 26, 28, 31, 33, 36, 39, 41, 44, 47,
       49, 52, 55])

### Mathematical operations are vectorized using numpy array

In [18]:
a1*2

array([ 4,  8, 12, 16])

### Mathematical operation across two numpy array

In [19]:
a1+a2

array([ 3. ,  6. ,  9. , 12.6])

### Creating a 2X2 two-dimensional array

In [20]:
a12 = [[1,2],[3,4]]
a12

[[1, 2], [3, 4]]

### Create two dimensional array using arange() and reshape() function

In [21]:
a13 = np.arange(0,10).reshape(5,2)
a13

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

#### Creation of two-dimensional array using linspace and reshape

In [22]:
a14 = np.linspace(0,51,50,dtype = int).reshape(5,10)
a14

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 51]])

#### Number of elements in array a14

In [23]:
np.size(a14)

50

#### Number of rows in array a13

In [24]:
np.size(a14,0)

5

#### Number of columns in array a13

In [25]:
np.size(a14,1)

10

In [26]:
np.size(a13,2)

IndexError: tuple index out of range

## Selecting array elements

#### Select 0 based array elements

In [ ]:
a1[0]

In [ ]:
a1[0],a1[2]

#### Accessing the 2 Dimensional array elements

In [ ]:
a14[3,4]

In [ ]:
a13[2,1]

### Selecting the entire row in 2D array element

In [ ]:
a13[2,]

In [ ]:
a14[3,]

### Selecting the entire column 2D array element

In [ ]:
a13[:,1]

#### Using a blank space in place of : will result in sytax error

In [ ]:
a14[:,3]

## Logical operations on arrays

### Which item are less than 5

In [ ]:
a15 = np.arange(10)
a15 < 5

#### Use complicated bolean expressions (element < 3 and element > 6)

In [ ]:
(a15<3)|(a15>6)

###### Use of np.vectorize() to apply an exp. or func. to all array elements in vectorized manner 

#### 1. first define the function

In [ ]:
def exp(x):
    return (x<3 or x>6)

#### Vectorize the above function for every element of array

In [ ]:
np.vectorize(exp)(a15)

#### 2. define function

In [ ]:
def exp2(x):
    return(x**2 < 10 or x**2 >50)

### Vectorize the above operation

In [ ]:
np.vectorize(exp2)(a15)

#### Boolean selection

In [ ]:
a16 = np.arange(10)
r = a16 < 5
a16[r]

#### Count the number of values less than 5 

###### np.sum treats True as 1 and False as 0

In [ ]:
np.sum(r)

#### Comparision of two one dimensional arrays

In [ ]:
a17 = np.arange(9,-1,-1)
a16>a17

##### Compare two 2 dimensional arrays

In [ ]:
a18 = np.arange(0,10).reshape(2,5)
a19 = np.arange(9,-1,-1).reshape(2,5)
a18>a19

## Slicing operation in Arrays

#### Slicing the 3rd to the 8th element of array

In [ ]:
a20 = np.arange(1,10)
a20[3:8]

#### Selecting every other element of array using step of slice

In [ ]:
a20[::2]

#### Completly reversing the array

In [ ]:
a20[::-1]

#### Prove that in Slicing the end element is not inclusive

In [ ]:
a20[9:0:-1]

#### Select all items from position 5

In [ ]:
a20[5:]

#### Select first 5 elements of the array

In [ ]:
a20[:5]

### Slicing a Two Dimensional array

In [ ]:
a21 = np.arange(1,21).reshape(5,4)
a21

### Position 1 element in all rows

In [ ]:
a21[:,1]

### Columns in position 1 and 2 of the entire matrix

In [ ]:
a21[:,1:3]

### Slicing the rows 

In [ ]:
a21[1:3,]

### Slicing rows and columns

In [ ]:
a21[1:3,2:4]

### Selecting specific rows and column

In [ ]:
a21[[0,2,4],1:4]

## Reshaping the array

#### Creating creating a 15X1 array then reshaping it to a 5X3 array back to 15X1 array 

In [ ]:
a22 = np.arange(1,16).reshape(5,3)
a22

#### The .reshape() cerates a new array and the orignal array remains unchanged 

In [ ]:
a22.reshape(1,15)
a22

In [ ]:
reshaped = a22.reshape(15)
reshaped

#### Using .ravel() method to create one dimensional array out of a 2D array

In [ ]:
raveled = a22.ravel()
raveled

#### The source remains unaffected

In [ ]:
a22

#### Changing reshaped and raveled, changes the source

In [ ]:
reshaped[4] = 50
reshaped[2] = 50
reshaped[5] = 50
raveled[11] = 100
raveled[13] =200
a22

#### The .flatten() method creates a new copy of the array

In [ ]:
flattened = a22.flatten()
flattened[7] = 500
flattened

#### Orignal array remains unaffected

In [ ]:
a22

#### The .shape property to return the shape of an array

In [ ]:
flattened.shape

#### Assigment operator can be used to allocate a new shape or reshaping

In [ ]:
flattened.shape = (5,3)
flattened

#### Calculation of Transpose of the Matrix

In [ ]:
flattened.transpose()

#### Transposing using `.T` property 

In [ ]:
flattened.T

#### The resizing of array can be done using .resize() method

In [ ]:
m = np.arange(1,10).reshape(3,3)
m

In [ ]:
m.resize(9)
m

## Combining Two arrays

#### Creating Two arrays for example

In [ ]:
a = np.arange(1,10).reshape(3,3)
a

In [ ]:
b = a*10+1
b

#### Combining two arrays using the hstack 

In [ ]:
np.hstack((a,b))

#### Merging Two arrays using the concatenate() function

In [ ]:
np.concatenate((a,b),axis = 1)

### Combining two arrays using vstack

In [ ]:
np.vstack((a,b))

#### Appending two arrays with concatenate

In [ ]:
np.concatenate((a,b),axis = 0)

##### Combining the two arrays using dstack (making a 3 dimensional array using two 2 dimensional array)

In [ ]:
np.dstack((a,b))

### Column stacking of two one dimensional array

In [ ]:
a1 = np.arange(10)
a2 = (a1+1)*10-6
a3 = (a1-1)*10+6
a1

In [ ]:
a2

In [ ]:
a3

In [ ]:
np.column_stack((a1,a2))

#### np.column_stack() and np.hstack() will not effectivly yeild same result

In [ ]:
np.hstack((a1,a2))

#### Column stack of more than 2 array is possible

In [ ]:
np.column_stack((a1,a2,a3))

#### column_stack for 3x3 and 3x4 array

In [ ]:
a1 = np.arange(12).reshape(3,4)
np.column_stack((a,a1))

#### hstack for 3x3 and 3x4 array

In [ ]:
np.hstack((a,a1))

#### row_stack of two array

In [ ]:
a2

In [ ]:
a3

In [ ]:
np.row_stack((a2,a3))

## Horizontal Split of Array

In [ ]:
a = np.arange(12).reshape(3,4)
a

#### Using second parameter to np.hslipt() as a scalar value 

In [ ]:
np.hsplit(a,4)

### Array can be split in any multiple of column

In [ ]:
np.hsplit(a,4)

##### if non multiple is used we recive a value error 

In [ ]:
np.hsplit(a,3)

#### Array split along specified column if list is passed

In [ ]:
np.hsplit(a,[1,3])

### Horizontal Split of array using split() function

In [ ]:
np.split(a,2,axis = 1)

#### Vetrical split of the above array

In [ ]:
np.vsplit(a,3)

#### row specific split can also be perfrmed

In [ ]:
np.vsplit(a,[1,3])

### The dsplit() of an array

In [ ]:
c = np.arange(27).reshape(3,3,3)
np.dsplit(c,3)

### Numerical methods of Numpy array

In [27]:
a = np.arange(11,32).reshape(3,7)
a

array([[11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31]])

In [28]:
print("{0} the min of entire matrix".format(a.min())) 

11 the min of entire matrix


In [29]:
print("{0} the max of entire matrix".format(a.max()))

31 the max of entire matrix


In [30]:
print("{} the position of minimum value in array".format(a.argmin()))

0 the position of minimum value in array


In [31]:
print("{} the position of maximum value in array".format(a.argmax()))

20 the position of maximum value in array


### Calculating the minimum and maximum along the specific axis

In [32]:
print("{0} are the minimum values along the columns".format(a.min(axis = 0)))

[11 12 13 14 15 16 17] are the minimum values along the columns


In [33]:
print("{0} are the maximum vales along the columns".format(a.max(axis=0)))

[25 26 27 28 29 30 31] are the maximum vales along the columns


In [34]:
print("{0} are the min values along the rows".format(a.min(axis = 1)))

[11 18 25] are the min values along the rows


In [35]:
print("{0} are the max values along the rows".format(a.max(axis = 1)))

[17 24 31] are the max values along the rows


#### Claculation of mean, standard deviation and variance of array

In [36]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Mean of above array

In [40]:
print("{0} is the mean of array b".format (b.mean()))

5.5 is the mean of array b


### Mean along each axis

In [41]:
print("{0} is the mean of each column".format(b.mean(axis = 0)))

[4. 5. 6. 7.] is the mean of each row


In [43]:
print("{0} is the mean of each row".format(b.mean(axis = 1)))

[1.5 5.5 9.5] is the mean of each row


### Standard deviation

In [97]:
b.std()

3.452052529534663

In [95]:
b.std(axis =0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [46]:
print("{0} is the standard deviation of array b".format (round(b.std(),2)))

3.45 is the standard deviation of array b


### Doubt 

In [98]:
print("{0} is the standard deviation of array b along each column".format (b.std(axis = 0)))

[3.26598632 3.26598632 3.26598632 3.26598632] is the standard deviation of array b along each column


In [54]:
print("{0} is the standard deviation of array b along each column".format (b.std(axis = 1)))

[1.11803399 1.11803399 1.11803399] is the standard deviation of array b along each column


### Variance 

In [55]:
print("{0} is the variance of array b".format (round(b.var(),2)))

11.92 is the variance of array b


#### Variance along axis

In [99]:
print("{0} is the variance of array b along x-axis".format (b.var(axis = 0),2))

[10.66666667 10.66666667 10.66666667 10.66666667] is the variance of array b along x-axis


In [58]:
print("{0} is the variance of array b along y-axis".format (b.var(axis = 0)))

[10.66666667 10.66666667 10.66666667 10.66666667] is the variance of array b along y-axis


### .sum() method

In [59]:
print("{0} is the sum of all elements in array b".format (b.sum()))

66 is the sum of all elements in array b


### summing along each axis

In [61]:
print("{0} is the sum of all elements in array b along column".format (b.sum(axis = 0)))

[12 15 18 21] is the sum of all elements in array b along column


In [63]:
print("{0} is the sum of all elements in array b along row".format (b.sum(axis = 1)))

[ 6 22 38] is the sum of all elements in array b along row


### .product() method

In [67]:
print("{0} is the product of all elements in array b".format(b.prod()))

0 is the product of all elements in array b


#### Product along the each axis

In [68]:
print("{0} is the product of all elements in array b along row".format (b.prod(axis = 1)))

[   0  840 7920] is the product of all elements in array b along row


In [69]:
print("{0} is the product of all elements in array b along column".format (b.prod(axis = 0)))

[  0  45 120 231] is the product of all elements in array b along column


### cumsum() and cumprod() methods

In [75]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### cummlative sm of a one dimensional array

In [76]:
c.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

### Cummlative sum of a two dimensional array

In [77]:
b.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66])

#### Cummlative sum along the column

In [72]:
b.cumsum(axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

#### Cummlative sum along the row

In [73]:
b.cumsum(axis = 1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

### The .all() and .any() method

In [79]:
d = np.arange(1,11)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Using any to check any member satisfying the condition

In [80]:
(d > 5).any()

True

In [83]:
(d>12).any()

False

### Using all to check any member satisfying the condition

In [84]:
(d<12).all()

True

In [85]:
(d<5).all()

False

### The .size property returns number of elements in array

In [87]:
b.size

12

In [88]:
d.size

10

### The .ndim property will give total number of dimensions

In [90]:
b.ndim

2

In [91]:
d.ndim

1