In [2]:
import numpy as np

In [3]:
#1D array
arr1 = np.array([1,2,3,4,5])

In [4]:
#2D array

arr2 =np.array([[1,2],[3,4]])

In [5]:
arr2

array([[1, 2],
       [3, 4]])

In [6]:
#3D array

arr3 =np.array([[[1,2],[3,4]],[[10,20],[30,40]]])

In [7]:
arr3

array([[[ 1,  2],
        [ 3,  4]],

       [[10, 20],
        [30, 40]]])

In [8]:
#check number of dimensions ndim

arr1.ndim

1

In [9]:
arr2.ndim

2

In [10]:
arr3.ndim

3

In [11]:
arr1

array([1, 2, 3, 4, 5])

In [12]:
arr1[0]

1

In [13]:
arr1[3]

4

In [14]:
arr2

array([[1, 2],
       [3, 4]])

In [15]:
arr2[1,1]

4

In [16]:
arr2[0,1]

2

In [17]:
arr3

array([[[ 1,  2],
        [ 3,  4]],

       [[10, 20],
        [30, 40]]])

In [18]:
#access 20

arr3[1,0,1]

20

In [19]:
#access the number 3
# for 3rd dim : 0
# for 2nd dim row: 1
# for 2nd dim col: 0

arr3[0,1,0]

3

In [20]:
#access 30

arr3[1,1,0]





30

In [21]:
#check shape

arr1.shape

(5,)

In [22]:
arr2.shape

(2, 2)

In [23]:
arr3.shape

(2, 2, 2)

In [24]:
#reshape

array1 = np.array([30,22,44,55,66,77])

In [25]:
array1.reshape(3,2)

array([[30, 22],
       [44, 55],
       [66, 77]])

In [26]:
#sort

s1 = np.sort(array1)

In [27]:
s1

array([22, 30, 44, 55, 66, 77])

In [28]:
#joining of arrays

a1 = np.array([11,22,33])
a2 = np.array([33,44,55])

In [29]:
a3 = np.concatenate((a1,a2))

In [30]:
a3

array([11, 22, 33, 33, 44, 55])

In [31]:
a4 = np.hstack((a1,a2))

In [32]:
a4

array([11, 22, 33, 33, 44, 55])

In [33]:
a5 = np.vstack((a1,a2))

In [34]:
a5

array([[11, 22, 33],
       [33, 44, 55]])

In [35]:
arr3

array([[[ 1,  2],
        [ 3,  4]],

       [[10, 20],
        [30, 40]]])

In [36]:
#where

np.where(arr3==40)

(array([1], dtype=int64), array([1], dtype=int64), array([1], dtype=int64))

In [38]:
arr3[1,1,1]

40

In [41]:
np.where(a5==22)

(array([0], dtype=int64), array([1], dtype=int64))