In [1]:
import pandas as pd
import numpy as np

+ Read Data

In [2]:
data = pd.read_csv('../datasets/PCA.csv',index_col='Univ')

In [3]:
data.head()

SAT  Top10  Accept  SFRatio  Expenses  GradRate
Univ                                                      
Brown     1310     89      22       13     22704        94
CalTech   1415    100      25        6     63575        81
CMU       1260     62      59        9     25026        72
Columbia  1310     76      24       12     31510        88
Cornell   1280     83      33       13     21864        90

## Standarize the data

In [4]:
from sklearn.preprocessing import scale

In [5]:
scaled_df = scale(data)

In [6]:
pd.DataFrame(scaled_df).head()

0         1         2         3         4         5
0  0.410284  0.657519 -0.889867  0.070260 -0.331413  0.820303
1  1.399259  1.235212 -0.734657 -1.686251  2.560381 -0.644524
2 -0.060657 -0.760454  1.024382 -0.933460 -0.167121 -1.658634
3  0.410284 -0.025208 -0.786394 -0.180670  0.291649  0.144229
4  0.127719  0.342414 -0.320766  0.070260 -0.390846  0.369587

## Build the Model

In [7]:
from sklearn.decomposition import PCA

In [8]:
model = PCA(n_components = 6)

+ Note:- even though it is being called a model but it is not a model in itself but it is a preprocessing step

In [9]:
pca_values = model.fit_transform(scaled_df)

In [10]:
pca_values

array([[-1.00987445e+00, -1.06430962e+00,  8.10663051e-02,
         5.69506350e-02, -1.28754245e-01, -3.46496377e-02],
       [-2.82223781e+00,  2.25904458e+00,  8.36828830e-01,
         1.43844644e-01, -1.25961913e-01, -1.80703168e-01],
       [ 1.11246577e+00,  1.63120889e+00, -2.66786839e-01,
         1.07507502e+00, -1.91814148e-01,  3.45679459e-01],
       [-7.41741217e-01, -4.21874699e-02,  6.05008649e-02,
        -1.57208116e-01, -5.77611392e-01,  1.09163092e-01],
       [-3.11912064e-01, -6.35243572e-01,  1.02405189e-02,
         1.71363672e-01,  1.27261287e-02, -1.69212696e-02],
       [-1.69669089e+00, -3.44363283e-01, -2.53407507e-01,
         1.25643278e-02, -5.26606002e-02, -2.71661600e-02],
       [-1.24682093e+00, -4.90983662e-01, -3.20938196e-02,
        -2.05643780e-01,  2.93505340e-01, -7.80119838e-02],
       [-3.38749784e-01, -7.85168589e-01, -4.93584829e-01,
         3.98563085e-02, -5.44978619e-01, -1.55371653e-01],
       [-2.37415013e+00, -3.86538883e-01,  1.160

In [12]:
var = model.explained_variance_ratio_
var

array([0.76868084, 0.13113602, 0.04776031, 0.02729668, 0.0207177 ,
       0.00440844])

In [13]:
np.cumsum(var)

array([0.76868084, 0.89981687, 0.94757718, 0.97487386, 0.99559156,
       1.        ])

+ with help of only three principal components we are able to explain 90% variance

In [14]:
final_model = PCA(n_components=3)

In [15]:
pca_values = final_model.fit_transform(scaled_df)

In [16]:
pca_values

array([[-1.00987445, -1.06430962,  0.08106631],
       [-2.82223781,  2.25904458,  0.83682883],
       [ 1.11246577,  1.63120889, -0.26678684],
       [-0.74174122, -0.04218747,  0.06050086],
       [-0.31191206, -0.63524357,  0.01024052],
       [-1.69669089, -0.34436328, -0.25340751],
       [-1.24682093, -0.49098366, -0.03209382],
       [-0.33874978, -0.78516859, -0.49358483],
       [-2.37415013, -0.38653888,  0.11609839],
       [-1.40327739,  2.11951503, -0.44282714],
       [-1.72610332,  0.08823712,  0.17040366],
       [-0.45085748, -0.01113295, -0.17574605],
       [ 0.04023814, -1.00920438, -0.49651717],
       [ 3.23373034, -0.37458049, -0.49537282],
       [-2.23626502, -0.37179329, -0.39899365],
       [ 5.17299212,  0.77991535, -0.38591233],
       [-1.69964377, -0.30559745,  0.31850785],
       [ 4.578146  , -0.34759136,  1.49964176],
       [ 0.82260312, -0.69890615,  1.42781145],
       [-0.09776213,  0.65044645,  0.10050844],
       [ 1.9631826 , -0.22476756, -0.255

In [17]:
var = final_model.explained_variance_ratio_
var

array([0.76868084, 0.13113602, 0.04776031])

In [18]:
np.cumsum(var)

array([0.76868084, 0.89981687, 0.94757718])